import React, { useEffect, useState } from "react";
import { pluginSettingsScopes, pluginViewPresentation, type PluginInstallation } from "../../../../plugins/sdk";
import { pluginRequest } from "./session-tab-controller";
import { PluginSettings } from "./plugin-settings";

type Operation = { id: string; pluginId: string; installationRevision: number; state: string; expiresAt?: string; impact?: unknown; diagnostic?: string };
export function PluginManagement({ onChanged, piboSessionId, agentId }: { onChanged: () => void; piboSessionId?: string; agentId?: string }) {
	const [installations, setInstallations] = useState<PluginInstallation[]>([]); const [operation, setOperation] = useState<Operation | null>(null); const [confirmation, setConfirmation] = useState(""); const [source, setSource] = useState(""); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [inspection, setInspection] = useState<string | null>(null);
	const load = async () => { const result = await pluginRequest<{ installations: PluginInstallation[] }>("/api/chat/plugins"); setInstallations(result.installations); };
	useEffect(() => { void load().catch((error) => setError(String(error))); }, []);
	const run = async (action: () => Promise<void>, refreshWorkspace = false) => { if (busy) return; setBusy(true); setError(null); try { await action(); await load(); if (refreshWorkspace) onChanged(); } catch (error) { setError(String(error)); } finally { setBusy(false); } };
	return <section className="space-y-3 text-xs" aria-label="Plugin management">
		<p className="text-slate-400">Manage installation and system activation here. Agent capabilities are selected separately in Agent Designer.</p>
		{installations.map((item) => {
			const agentContributions = item.manifest.contributions.filter((contribution) => contribution.scope === "agent");
			const systemContributions = item.manifest.contributions.filter((contribution) => contribution.scope === "app");
			const workspaceModules = item.manifest.contributions.filter((contribution) => contribution.view && pluginViewPresentation(contribution.view) === "workspace");
			const scopes = pluginSettingsScopes(item.manifest);
			return <details className="border border-slate-700 bg-[#151f24]" key={item.pluginId}>
				<summary className="cursor-pointer p-3"><span className="flex flex-wrap items-start justify-between gap-2"><span><span className="block text-sm font-semibold text-slate-100">{item.manifest.name}</span><span className="text-slate-500">Version {item.version}</span></span><span className={`border px-2 py-0.5 uppercase tracking-wider ${item.enabled && item.state === "active" ? "border-emerald-600/60 text-emerald-200" : "border-amber-600/60 text-amber-100"}`}>{item.enabled && item.state === "active" ? "Active" : item.state.replaceAll("-", " ")}</span></span></summary>
				<div className="space-y-2 border-t border-slate-800 p-3">
					<div className="flex flex-wrap gap-1 text-[10px] uppercase tracking-wider text-slate-400">
						{systemContributions.length || item.manifest.services?.provides?.length ? <span className="border border-slate-700 px-1.5 py-0.5">System functionality</span> : null}
						{agentContributions.length ? <span className="border border-sky-800 px-1.5 py-0.5 text-sky-200">{agentContributions.length} agent {agentContributions.length === 1 ? "capability" : "capabilities"}</span> : null}
						{workspaceModules.length ? <span className="border border-slate-700 px-1.5 py-0.5">{workspaceModules.length} workspace {workspaceModules.length === 1 ? "module" : "modules"}</span> : null}
						{item.manifest.config ? <span className="border border-slate-700 px-1.5 py-0.5">Configurable</span> : null}
					</div>
					<div className="flex flex-wrap gap-2"><button disabled={busy || item.state === "uninstalled"} onClick={() => void run(async () => { setOperation(await pluginRequest<Operation>(`/api/chat/plugins/${encodeURIComponent(item.pluginId)}/uninstall-plan`, { method: "POST", body: "{}" })); setConfirmation(""); })}>Plan uninstall</button><button disabled={busy || !["installed", "pending-activation", "failed"].includes(item.state)} onClick={() => void run(async () => { setOperation(await pluginRequest<Operation>(`/api/chat/plugins/${encodeURIComponent(item.pluginId)}/activate`, { method: "POST", body: JSON.stringify({ expectedRevision: item.stateRevision }) })); }, true)}>Activate system side</button></div>
					<details className="border-t border-slate-800 pt-2"><summary className="cursor-pointer text-sky-300">Configuration</summary>{item.manifest.config ? <PluginSettings pluginId={item.pluginId} piboSessionId={piboSessionId} agentId={agentId} scopes={scopes} /> : <p className="mt-2 text-slate-500">This plugin declares no configurable options.</p>}</details>
				</div>
			</details>;
		})}
		{operation ? <div className="border border-orange-500/40 p-2 space-y-2"><h3>Operation {operation.state}</h3><p className="font-mono break-all">{operation.id}</p><pre className="whitespace-pre-wrap break-all">{JSON.stringify(operation.impact, null, 2)}</pre><p>{operation.diagnostic}</p><p>Expires: {operation.expiresAt ?? "not applicable"}</p><label>Confirm exact plugin ID<input className="w-full bg-[#151f24] border border-slate-600 p-1" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} /></label><button disabled={busy || confirmation !== operation.pluginId} onClick={() => void run(async () => { setOperation(await pluginRequest<Operation>("/api/chat/plugins/uninstall-confirm", { method: "POST", body: JSON.stringify({ planId: operation.id, pluginIdText: confirmation, expectedRevision: operation.installationRevision }) })); }, true)}>Confirm retained-data uninstall</button><button className="ml-2" disabled={busy} onClick={() => void run(async () => { setOperation(await pluginRequest<Operation>(`/api/chat/plugins/operations/${encodeURIComponent(operation.id)}/resume`, { method: "POST", body: "{}" })); }, true)}>Resume / check drain</button><button className="ml-2" disabled={busy} onClick={() => void run(async () => { setOperation(await pluginRequest<Operation>(`/api/chat/plugins/operations/${encodeURIComponent(operation.id)}/cancel`, { method: "POST", body: "{}" })); }, true)}>Cancel operation</button></div> : null}
		<details><summary>Inspect / install trusted source</summary><p>Plugins execute trusted code. Provide a local source object or an exact package artifact; inspect first.</p><textarea aria-label="Plugin source JSON" value={source} onChange={(event) => { setSource(event.target.value); setInspection(null); }} placeholder={'{"kind":"local","path":"/path/to/plugin"}'} className="w-full bg-[#0e1116] font-mono" /><button disabled={busy || !source} onClick={() => void run(async () => { setInspection(JSON.stringify(await pluginRequest("/api/chat/plugins/inspect", { method: "POST", body: JSON.stringify({ source: JSON.parse(source) }) }), null, 2)); })}>Inspect without import</button>{inspection ? <><pre className="whitespace-pre-wrap break-all">{inspection}</pre><button disabled={busy} onClick={() => void run(async () => { await pluginRequest("/api/chat/plugins/install", { method: "POST", body: JSON.stringify({ source: JSON.parse(source), expectedRevision: 0 }) }); setInspection(null); }, true)}>Install inspected new plugin</button></> : null}</details>
		{error ? <p role="alert" className="text-orange-300">{error}</p> : null}
	</section>;
}
