import React, { useEffect, useState } from "react";
import type { PluginInstallation } from "../../../../plugins/sdk";
import { pluginRequest } from "./session-tab-controller";

type Operation = { id: string; pluginId: string; installationRevision: number; state: string; expiresAt?: string; impact?: unknown; diagnostic?: string };
export function PluginManagement({ onChanged }: { onChanged: () => void }) {
	const [installations, setInstallations] = useState<PluginInstallation[]>([]); const [operation, setOperation] = useState<Operation | null>(null); const [confirmation, setConfirmation] = useState(""); const [source, setSource] = useState(""); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [inspection, setInspection] = useState<string | null>(null);
	const load = async () => { const result = await pluginRequest<{ installations: PluginInstallation[] }>("/api/chat/plugins"); setInstallations(result.installations); };
	useEffect(() => { void load().catch((error) => setError(String(error))); }, []);
	const run = async (action: () => Promise<void>, refreshWorkspace = false) => { if (busy) return; setBusy(true); setError(null); try { await action(); await load(); if (refreshWorkspace) onChanged(); } catch (error) { setError(String(error)); } finally { setBusy(false); } };
	return <section className="p-3 border-b border-slate-700 max-h-[60vh] overflow-auto space-y-2 text-xs" aria-label="Plugin management">
		<h2 className="uppercase font-bold">Installed plugins</h2><p className="text-slate-400">Installation does not enable agent contributions. Uninstall retains sessions, history, tab state, and user files.</p>
		{installations.map((item) => <div className="border border-slate-700 p-2 space-y-1" key={item.pluginId}><p className="font-mono break-all">{item.pluginId} · {item.version}</p><p>{item.state} · revision {item.stateRevision}</p><div className="flex gap-2"><button disabled={busy || item.state === "uninstalled"} onClick={() => void run(async () => { setOperation(await pluginRequest<Operation>(`/api/chat/plugins/${encodeURIComponent(item.pluginId)}/uninstall-plan`, { method: "POST", body: "{}" })); setConfirmation(""); })}>Plan uninstall</button><button disabled={busy || !["installed", "pending-activation", "failed"].includes(item.state)} onClick={() => void run(async () => { setOperation(await pluginRequest<Operation>(`/api/chat/plugins/${encodeURIComponent(item.pluginId)}/activate`, { method: "POST", body: JSON.stringify({ expectedRevision: item.stateRevision }) })); }, true)}>Activate</button></div></div>)}
		{operation ? <div className="border border-orange-500/40 p-2 space-y-2"><h3>Operation {operation.state}</h3><p className="font-mono break-all">{operation.id}</p><pre className="whitespace-pre-wrap break-all">{JSON.stringify(operation.impact, null, 2)}</pre><p>{operation.diagnostic}</p><p>Expires: {operation.expiresAt ?? "not applicable"}</p><label>Confirm exact plugin ID<input className="w-full bg-[#151f24] border border-slate-600 p-1" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} /></label><button disabled={busy || confirmation !== operation.pluginId} onClick={() => void run(async () => { setOperation(await pluginRequest<Operation>("/api/chat/plugins/uninstall-confirm", { method: "POST", body: JSON.stringify({ planId: operation.id, pluginIdText: confirmation, expectedRevision: operation.installationRevision }) })); }, true)}>Confirm retained-data uninstall</button><button className="ml-2" disabled={busy} onClick={() => void run(async () => { setOperation(await pluginRequest<Operation>(`/api/chat/plugins/operations/${encodeURIComponent(operation.id)}/resume`, { method: "POST", body: "{}" })); }, true)}>Resume / check drain</button><button className="ml-2" disabled={busy} onClick={() => void run(async () => { setOperation(await pluginRequest<Operation>(`/api/chat/plugins/operations/${encodeURIComponent(operation.id)}/cancel`, { method: "POST", body: "{}" })); }, true)}>Cancel operation</button></div> : null}
		<details><summary>Inspect / install trusted source</summary><p>Plugins execute trusted code. Provide a local source object or an exact package artifact; inspect first.</p><textarea aria-label="Plugin source JSON" value={source} onChange={(event) => { setSource(event.target.value); setInspection(null); }} placeholder={'{"kind":"local","path":"/path/to/plugin"}'} className="w-full bg-[#0e1116] font-mono" /><button disabled={busy || !source} onClick={() => void run(async () => { setInspection(JSON.stringify(await pluginRequest("/api/chat/plugins/inspect", { method: "POST", body: JSON.stringify({ source: JSON.parse(source) }) }), null, 2)); })}>Inspect without import</button>{inspection ? <><pre className="whitespace-pre-wrap break-all">{inspection}</pre><button disabled={busy} onClick={() => void run(async () => { await pluginRequest("/api/chat/plugins/install", { method: "POST", body: JSON.stringify({ source: JSON.parse(source), expectedRevision: 0 }) }); setInspection(null); }, true)}>Install inspected new plugin</button></> : null}</details>
		{error ? <p role="alert" className="text-orange-300">{error}</p> : null}
	</section>;
}
