export type CodexAppServerJson =
	| null
	| boolean
	| number
	| string
	| CodexAppServerJson[]
	| { [key: string]: CodexAppServerJson };

export type CodexAppServerRequestId = string | number;

export type CodexAppServerClientInfo = {
	name: string;
	title?: string | null;
	version: string;
};

/** Stable initialize capabilities generated by Codex App Server 0.147.0. */
export type CodexAppServerInitializeCapabilities = {
	experimentalApi?: boolean;
	extensions?: Record<string, CodexAppServerJson> | null;
	mcpServerOpenaiFormElicitation?: boolean;
	optOutNotificationMethods?: string[] | null;
	requestAttestation?: boolean;
};

export type CodexAppServerInitializeParams = {
	clientInfo: CodexAppServerClientInfo;
	capabilities?: CodexAppServerInitializeCapabilities | null;
};

export type CodexAppServerInitializeResponse = {
	codexHome: string;
	platformFamily: string;
	platformOs: string;
	userAgent: string;
};

export type CodexAppServerRpcError = {
	code: number;
	message: string;
	data?: CodexAppServerJson;
};

export type CodexAppServerClientRequest<TParams = CodexAppServerJson> = {
	id: CodexAppServerRequestId;
	method: string;
	params?: TParams;
};

export type CodexAppServerClientNotification<TParams = CodexAppServerJson> = {
	method: string;
	params?: TParams;
};

export type CodexAppServerSuccessResponse<TResult = CodexAppServerJson> = {
	id: CodexAppServerRequestId;
	result: TResult;
};

export type CodexAppServerErrorResponse = {
	id: CodexAppServerRequestId;
	error: CodexAppServerRpcError;
};

export type CodexAppServerResponse<TResult = CodexAppServerJson> =
	| CodexAppServerSuccessResponse<TResult>
	| CodexAppServerErrorResponse;

export type CodexAppServerServerRequest<TParams = CodexAppServerJson> = {
	id: CodexAppServerRequestId;
	method: string;
	params?: TParams;
};

export type CodexAppServerServerNotification<TParams = CodexAppServerJson> = {
	method: string;
	params?: TParams;
};
