import { useMemo, useState, type ReactNode } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Activity, AlertTriangle, CheckCircle2, Clock3, Database, ExternalLink, GitBranch, Loader2, Play, RefreshCw, Route } from "lucide-react";
import { getSessionWorkflow, postWorkflowHumanAction, postWorkflowSessionStart, type SessionWorkflowInspectionResponse } from "../api-workflows";
import { errorMessage } from "../error-message";
import { JsonRenderer } from "../tracing/JsonRenderer";
import type { PiboWorkflowPendingHumanAction, PiboWorkflowWaitToken } from "../types";
import { shortWorkflowId, workflowStateBadgeClass } from "../workflows/workflow-session-model";
import type { ChatSessionViewProps } from "./types";

export function WorkflowXStateSessionView({ selectedPiboSessionId, workflowSessionLinked, sessionNodes, onOpenSession, onRefreshBootstrap, onError }: ChatSessionViewProps) {
  const queryClient = useQueryClient();
  const queryKey = ["chat", "session-workflow", selectedPiboSessionId] as const;
  const inspection = useQuery({ queryKey, queryFn: () => getSessionWorkflow(selectedPiboSessionId!), enabled: Boolean(selectedPiboSessionId && workflowSessionLinked), retry: false });
  const [starting, setStarting] = useState(false);
  const [actionBusy, setActionBusy] = useState<string>();
  const [message, setMessage] = useState<string>();
  const data = inspection.data;
  const refresh = async () => { await Promise.all([inspection.refetch(), onRefreshBootstrap?.()]); };
  const start = async () => {
    if (!selectedPiboSessionId || starting) return;
    setStarting(true); setMessage(undefined); onError?.(null);
    try { const result = await postWorkflowSessionStart(selectedPiboSessionId); setMessage(result.alreadyStarted ? "Workflow run was already started." : result.message || "Workflow run started."); await queryClient.invalidateQueries({ queryKey }); await refresh(); }
    catch (caught) { onError?.(errorMessage(caught)); }
    finally { setStarting(false); }
  };
  const submitAction = async (waitTokenId: string, actionId: string | undefined, kind: string | undefined, payload: unknown) => {
    if (!selectedPiboSessionId) return;
    setActionBusy(`${waitTokenId}:${actionId ?? kind ?? "resume"}`); onError?.(null);
    try { await postWorkflowHumanAction(selectedPiboSessionId, { waitTokenId, ...(actionId ? { actionId } : {}), ...(kind ? { kind } : {}), ...(payload !== undefined ? { payload } : {}) }); setMessage("Human action accepted."); await queryClient.invalidateQueries({ queryKey }); await refresh(); }
    catch (caught) { onError?.(errorMessage(caught)); }
    finally { setActionBusy(undefined); }
  };

  if (!workflowSessionLinked) return <WorkflowMessage title="Workflow unavailable">This normal Session has no workflow linkage. Workflow inspection is requested only for linked Sessions.</WorkflowMessage>;
  if (inspection.isLoading) return <WorkflowMessage title="Loading Workflow"><Loader2 className="inline animate-spin text-[#11a4d4]" size={15} /> Loading configuration and run facts…</WorkflowMessage>;
  if (inspection.error || !data) return <WorkflowMessage title="Workflow inspection failed" error>{errorMessage(inspection.error ?? "No workflow inspection response")}</WorkflowMessage>;
  const link = data.workflowSession;
  const definitionLink = link.workflowDefinitionLink;
  const definitionHref = definitionLink?.status === "live" ? definitionLink.href ?? (link.workflowVersion ? `/apps/chat/workflows/view/${encodeURIComponent(link.workflowId)}/${encodeURIComponent(link.workflowVersion)}` : undefined) : undefined;
  const childSessions = collectWorkflowChildren(sessionNodes, link.piboSessionId);
  return <section className="min-w-0 flex-1 overflow-auto bg-[#0b0f14] p-4 text-slate-300" data-pibo-debug="session-native-workflow-view">
    <div className="mx-auto flex max-w-6xl flex-col gap-4">
      <header className="rounded-sm border border-slate-800 bg-[#111820] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2 font-semibold text-slate-100"><Activity size={16} className="text-[#11a4d4]" />Workflow Session</div><div className="mt-2 flex flex-wrap gap-2 text-xs"><Badge>{link.workflowId}{link.workflowVersion ? `@${link.workflowVersion}` : ""}</Badge><span className={workflowStateBadgeClass(link.state)}>{link.state}</span>{link.workflowRunId ? <Badge>run {shortWorkflowId(link.workflowRunId)}</Badge> : null}</div><p className="mt-2 text-xs text-slate-500">This is a normal Pibo Session with Workflow-owned linkage and execution facts.</p></div><div className="flex gap-2"><button type="button" onClick={() => void refresh()} disabled={inspection.isFetching} aria-label="Refresh Workflow state" className={buttonClass}>{inspection.isFetching ? <Loader2 size={13} className="animate-spin" /> : <RefreshCw size={13} />}Refresh</button>{link.state === "configured" && !link.workflowRunId ? <button type="button" onClick={() => void start()} disabled={starting} className={`${buttonClass} border-emerald-600 text-emerald-200`}>{starting ? <Loader2 size={13} className="animate-spin" /> : <Play size={13} />}Start Workflow</button> : null}</div></div>{message ? <div role="status" className="mt-3 rounded-sm border border-emerald-800 bg-emerald-950/20 p-2 text-xs text-emerald-200">{message}</div> : null}</header>
      <div className="rounded-sm border border-amber-800/60 bg-amber-950/15 p-3 text-xs leading-5 text-amber-100/80" aria-label="Workflow execution boundary">Workflow execution uses published Pibo Workflow IR and registered capabilities. XState is a read-only visualization; this surface does not expose inline code, raw XState editing, or broaden Session profile permissions.</div>
      <div className="grid gap-4 lg:grid-cols-2"><FactPanel icon={Database} title="Configuration"><JsonRenderer value={link.configuration ?? {}} /></FactPanel><FactPanel icon={Activity} title="Current run">{data.run ? <JsonRenderer value={data.run} /> : <Empty>No run exists. Start remains explicit.</Empty>}</FactPanel><FactPanel icon={CheckCircle2} title="Final output">{data.run && Object.hasOwn(data.run, "output") ? <JsonRenderer value={data.run.output} /> : <Empty>No final Workflow output recorded.</Empty>}</FactPanel><FactPanel icon={AlertTriangle} title="Validation and diagnostics"><JsonRenderer value={{ snapshotValidation: data.snapshot?.validation, lifecycleDiagnostics: data.lifecycleEvents.flatMap((event) => event.diagnostics ?? []) }} /></FactPanel></div>
      <WorkflowGraph snapshot={data.snapshot} attempts={data.nodeAttempts} transfers={data.edgeTransfers} />
      <HumanActions data={data} busy={actionBusy} onSubmit={submitAction} />
      <div className="grid gap-4 xl:grid-cols-2"><RecordList title="Node attempts" icon={CheckCircle2} records={data.nodeAttempts} empty="No node attempts recorded." /><RecordList title="Edge transfers" icon={Route} records={data.edgeTransfers} empty="No edge transfers recorded." /><RecordList title="Wait tokens" icon={Clock3} records={data.waitTokens} empty="No workflow waits recorded." /><RecordList title="Human action history" icon={Activity} records={data.humanActions} empty="No human actions recorded." /><RecordList title="Lifecycle events" icon={GitBranch} records={data.lifecycleEvents} empty="No lifecycle events recorded." /><FactPanel icon={Database} title="Immutable effective snapshot">{data.snapshot ? <JsonRenderer value={data.snapshot} /> : <Empty>No immutable snapshot is available.</Empty>}</FactPanel></div>
      <section className="rounded-sm border border-slate-800 bg-[#111820] p-4"><div className="flex items-center justify-between gap-3"><h2 className="text-xs font-bold uppercase tracking-wider text-slate-300">Workflow links</h2>{definitionHref ? <a href={definitionHref} className={buttonClass}><ExternalLink size={13} />Open definition</a> : null}</div>{definitionLink?.status === "snapshot_only_definition_deleted" ? <div className="mt-3 rounded-sm border border-amber-800 bg-amber-950/20 p-3 text-xs text-amber-100">{definitionLink.tombstoneLabel ?? "The live definition is unavailable. Inspection uses the immutable Session snapshot."}</div> : null}<div className="mt-3 grid gap-2">{childSessions.length ? childSessions.map((child) => <button key={child.piboSessionId} type="button" onClick={() => onOpenSession(child.piboSessionId)} className="rounded-sm border border-slate-800 bg-[#0e1116] p-3 text-left text-xs hover:border-[#11a4d4]"><span className="font-semibold text-slate-200">{child.title}</span><span className="ml-2 font-mono text-slate-500">{child.piboSessionId}</span></button>) : <Empty>No linked child Workflow Sessions.</Empty>}</div></section>
    </div>
  </section>;
}

function HumanActions({ data, busy, onSubmit }: { data: SessionWorkflowInspectionResponse; busy?: string; onSubmit: (waitTokenId: string, actionId: string | undefined, kind: string | undefined, payload: unknown) => Promise<void> }) {
  const pending = data.workflowSession.pendingHumanActions ?? [];
  const pendingTokens = data.waitTokens.filter((token) => !token.status || token.status === "pending" || token.status === "waiting");
  return <section className="rounded-sm border border-amber-800/60 bg-[#111820] p-4" aria-label="Workflow human actions"><h2 className="text-xs font-bold uppercase tracking-wider text-amber-200">Human actions</h2><div className="mt-3 grid gap-3">{pending.length ? pending.map((action) => <PendingAction key={action.waitTokenId} action={action} busy={busy} onSubmit={onSubmit} />) : pendingTokens.length ? pendingTokens.map((token) => <GenericWaitAction key={token.id} token={token} busy={busy} onSubmit={onSubmit} />) : <Empty>No pending human action.</Empty>}</div></section>;
}
function PendingAction({ action, busy, onSubmit }: { action: PiboWorkflowPendingHumanAction; busy?: string; onSubmit: (waitTokenId: string, actionId: string | undefined, kind: string | undefined, payload: unknown) => Promise<void> }) {
  const [payload, setPayload] = useState("{}"); const [payloadError, setPayloadError] = useState<string>();
  const invoke = (id?: string, kind?: string) => { let value: unknown; try { value = payload.trim() ? JSON.parse(payload) : undefined; setPayloadError(undefined); } catch { setPayloadError("Payload must be valid JSON."); return; } void onSubmit(action.waitTokenId, id, kind, value); };
  return <div className="rounded-sm border border-amber-700/50 bg-amber-950/10 p-3 text-xs"><div className="font-semibold text-amber-100">{action.prompt}</div>{action.diagnostics.length ? <div role="alert" className="mt-2 rounded-sm border border-red-800/70 bg-red-950/20 p-2 text-red-200"><JsonRenderer value={action.diagnostics} /></div> : null}{action.payloadRequirements.required || action.schema ? <><textarea aria-label={`Human action payload for ${action.waitTokenId}`} value={payload} onChange={(e) => setPayload(e.target.value)} className="mt-3 min-h-20 w-full rounded-sm border border-slate-700 bg-[#0e1116] p-2 font-mono text-xs" />{payloadError ? <div role="alert" className="mt-1 text-red-300">{payloadError}</div> : null}</> : null}<div className="mt-3 flex flex-wrap gap-2">{action.availableActions.map((choice) => <button key={choice.id} type="button" disabled={Boolean(busy)} onClick={() => invoke(choice.id, choice.kind)} className={buttonClass}>{choice.displayName}</button>)}</div></div>;
}
function GenericWaitAction({ token }: { token: PiboWorkflowWaitToken; busy?: string; onSubmit: (waitTokenId: string, actionId: string | undefined, kind: string | undefined, payload: unknown) => Promise<void> }) { return <div className="rounded-sm border border-amber-700/50 p-3 text-xs"><div>{token.prompt ?? `Wait ${token.id}`}</div><div className="mt-2 text-[11px] text-amber-100/70">No registered actions were returned for this wait token. Refresh after the runtime publishes actionable metadata.</div></div>; }
function WorkflowGraph({ snapshot, attempts, transfers }: { snapshot: SessionWorkflowInspectionResponse["snapshot"]; attempts: SessionWorkflowInspectionResponse["nodeAttempts"]; transfers: SessionWorkflowInspectionResponse["edgeTransfers"] }) {
  const graph = useMemo(() => graphFacts(snapshot), [snapshot]);
  if (!snapshot) return <FactPanel icon={GitBranch} title="Workflow graph"><Empty>No immutable snapshot is available, so no graph is rendered.</Empty></FactPanel>;
  return <FactPanel icon={GitBranch} title="Workflow graph"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{graph.nodes.map((node) => { const latest = [...attempts].reverse().find((attempt) => attempt.nodeId === node.id); return <div key={node.id} className="rounded-sm border border-slate-700 bg-[#0e1116] p-3 text-xs"><div className="font-mono font-semibold text-[#8bdcf4]">{node.id}</div><div className="mt-1 text-slate-400">{node.kind}</div><div className="mt-2 text-[10px] uppercase text-slate-500">{latest?.status ?? "not attempted"}</div></div>; })}</div>{graph.nodes.length === 0 ? <Empty>The snapshot contains no graph nodes.</Empty> : null}<div className="mt-3 grid gap-1 text-xs text-slate-400">{graph.edges.map((edge) => <div key={edge.id} className="rounded-sm border border-slate-800 p-2 font-mono">{edge.source} → {edge.target}{transfers.some((transfer) => transfer.edgeId === edge.id) ? " · transferred" : ""}</div>)}</div></FactPanel>;
}
function graphFacts(snapshot: SessionWorkflowInspectionResponse["snapshot"]): { nodes: { id: string; kind: string }[]; edges: { id: string; source: string; target: string }[] } { const definition = snapshot?.effectiveDefinition; if (!definition || typeof definition !== "object") return { nodes: [], edges: [] }; const nodesRaw = definition.nodes; const edgesRaw = definition.edges; const nodes = nodesRaw && typeof nodesRaw === "object" && !Array.isArray(nodesRaw) ? Object.entries(nodesRaw).map(([id, raw]) => ({ id, kind: valueString(raw, "kind") ?? "node" })) : []; const edges = edgesRaw && typeof edgesRaw === "object" && !Array.isArray(edgesRaw) ? Object.entries(edgesRaw).map(([id, raw]) => ({ id, source: nestedNodeId(raw, "from") ?? valueString(raw, "source") ?? "?", target: nestedNodeId(raw, "to") ?? valueString(raw, "target") ?? "?" })) : Array.isArray(edgesRaw) ? edgesRaw.map((raw, index) => ({ id: valueString(raw, "id") ?? `edge-${index + 1}`, source: nestedNodeId(raw, "from") ?? valueString(raw, "source") ?? "?", target: nestedNodeId(raw, "to") ?? valueString(raw, "target") ?? "?" })) : []; return { nodes, edges }; }
function valueString(value: unknown, key: string): string | undefined { if (!value || typeof value !== "object") return undefined; const item = (value as Record<string, unknown>)[key]; return typeof item === "string" ? item : undefined; }
function nestedNodeId(value: unknown, key: "from" | "to"): string | undefined { if (!value || typeof value !== "object") return undefined; return valueString((value as Record<string, unknown>)[key], "nodeId"); }
function collectWorkflowChildren(nodes: ChatSessionViewProps["sessionNodes"], parentId: string) { const found: { piboSessionId: string; title: string }[] = []; const visit = (items: ChatSessionViewProps["sessionNodes"]) => { for (const node of items) { if (node.parentId === parentId && (node.workflowSessionKind === "nested_workflow" || node.workflowSessionKind === "agent_node")) found.push({ piboSessionId: node.piboSessionId, title: node.title }); visit(node.children); } }; visit(nodes); return found; }
function RecordList({ title, icon: Icon, records, empty }: { title: string; icon: typeof Activity; records: unknown[]; empty: string }) { return <FactPanel icon={Icon} title={title}>{records.length ? <div className="grid gap-2">{records.map((record, index) => <div key={recordId(record, index)} className="rounded-sm border border-slate-800 bg-[#0e1116] p-2"><JsonRenderer value={record} /></div>)}</div> : <Empty>{empty}</Empty>}</FactPanel>; }
function FactPanel({ icon: Icon, title, children }: { icon: typeof Activity; title: string; children: ReactNode }) { return <section className="min-w-0 rounded-sm border border-slate-800 bg-[#111820] p-4"><h2 className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-300"><Icon size={14} className="text-[#11a4d4]" />{title}</h2>{children}</section>; }
function WorkflowMessage({ title, children, error = false }: { title: string; children: ReactNode; error?: boolean }) { return <section className="min-w-0 flex-1 overflow-auto bg-[#0b0f14] p-4"><div className={`mx-auto max-w-3xl rounded-sm border p-4 text-sm ${error ? "border-red-900 bg-red-950/30 text-red-200" : "border-slate-800 bg-[#111820] text-slate-300"}`}><div className="mb-2 flex items-center gap-2 font-semibold">{error ? <AlertTriangle size={15} /> : null}{title}</div>{children}</div></section>; }
function Empty({ children }: { children: ReactNode }) { return <div className="rounded-sm border border-dashed border-slate-700 p-3 text-xs text-slate-500">{children}</div>; }
function Badge({ children }: { children: ReactNode }) { return <span className="rounded border border-slate-700 bg-slate-900/40 px-2 py-1 font-mono text-slate-300">{children}</span>; }
function recordId(record: unknown, index: number) { return record && typeof record === "object" && typeof (record as { id?: unknown }).id === "string" ? (record as { id: string }).id : String(index); }
const buttonClass = "inline-flex items-center justify-center gap-1 rounded-sm border border-slate-700 px-3 py-1.5 text-xs font-semibold text-slate-200 hover:border-[#11a4d4] hover:text-white disabled:opacity-50";
